enclave:
  spid:        # Service Provider ID
  certificate: # Service Provider Certificate
  key:         # Service Provider Key
  iasHost:     # IAS Host to talk to (testing or production)
  acceptGroupOutOfDate: # Whether to serve IAS responses with GROUP_OUT_OF_DATE instead of OK [true|false]
  instances:
   - mrenclave: # mrenclave value 1
     debug:     # Whether this is a debug or production enclave [true|false]
   - mrenclave: # mrenclave value 2
     debug:     # Whether this is a debug or production enclave [true|false]

signal:
  userToken:    # head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'
  serverToken:  # head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'

redis:
  masterName:   # Redis Sentinel master name
  sentinelUrls:
   - # Redis Sentinel host:port 1
   - # Redis Sentinel host:port 2

directory:
  initialSize: 10000000
  minLoadFactor: 0.75
  maxLoadFactor: 0.85

limits:
  contactQueries:
    bucketSize:        # Leaky bucket size
    leakRatePerMinute: # Leaky bucket rate per minute
  remoteAttestations:
    bucketSize:        # Leaky bucket size
    leakRatePerMinute: # Leaky bucket rate per minute

metrics:
  reporters:
    - type:     json # wavefront metrics reporter
      hostname:      # wavefront endpoint hostname
      token:         # wavefront endpoint token
